### ISSUE TITLE
Comparing rows with different number of cells containing value

### ISSUE THREAD

**Issue by vlaci002** [tobyweston/simple-excel#12]
I use WorkbookMatcher.sameWorkbook(Workbook) to compare a result workbook against an expected one.
In case the same sheet in both of the workbooks contain a row (at the same position) that has the same number of cells (last cell is the same) but the resulting row contains one physical cell (cell with value) that is not existing in expected row then comparing will not find this difference.

The reason is that CellNumberMatcher only checks whether the last cells in the two rows are the same, RowInSheetMatcher checks actual row against expected row calling CellsMatcher and CellsMatcher matches the physical cells of the expected row.

I advise checking the equality of the number of physical cells in the rows in CellNumberMatcher.

**Comment by vlaci002** [comment]
I created a Pull Request with modification of CellNumberMatcher to resolve this issue. I also added a new test for this matcher.

**Comment by tobyweston** [comment]
Great, thanks very much. Will aim to merge this in asap.

**Comment by tobyweston** [comment]
This warrants a release (which may take me longer to remember how to do). I'll close the ticket once I've prepared a release. Thanks again.

**Comment by tobyweston** [comment]
Release as part of https://github.com/tobyweston/simple-excel/releases/tag/simple-excel-1.1

**Comment by vlaci002** [comment]
At your service, I'm glad I could contribute. 👍
