### ISSUE TITLE
Support for apache poi 4

### ISSUE THREAD

**Issue by leansh** [tobyweston/simple-excel#17]
Hi, are there plans to support apache poi 4? 
I'm not sure what changes that would entail

**Comment by michalaron** [comment]
I would be also very interested in version with poi 4 supported.

**Comment by tobyweston** [comment]
I think there's been some API changes in 4.x, so best to change the `pom` and see what breaks...

**Comment by tobyweston** [comment]
I've added support for 4.1.0 and released v1.2 (https://github.com/tobyweston/simple-excel/releases). Have a go and report back.

I haven't tested it against projects I'm using so there well might be problems, things I will change. I'll do a 1.2.x release if required.

PS. are there specific features of 4.x that you want to use?
