### ISSUE TITLE
Publish to Central Maven Repo

### ISSUE THREAD

**Issue by nsdiv** [tobyweston/simple-excel#6]
Would be easier to adopt this library if it was published to http://search.maven.org/. Most IT orgs do not like artifacts to be pulled from a different central repo.

**Comment by tobyweston** [comment]
Sorry, OSS Sonatype and I [disagree on what's a valid organisation Id is]()https://issues.sonatype.org/browse/OSSRH-2534 so I can't publish to Maven with my organisation Id.

You can add repositories to your `settings.xml` or request your org add it to their proxy / internal repository. Simple excel is available via my Maven repository at [http://robotooling.com/maven/](http://robotooling.com/maven/)

Something like this should do

```
<repositories>
    <repository>
        <id>bad.robot</id>
        <name>bad.robot repository on robotooling</name>
        <url>http://www.robotooling.com/maven/</url>
        <snapshots>
            <enabled>true</enabled>
            <updatePolicy>always</updatePolicy>
        </snapshots>
    </repository>
</repositories>
```
