### ISSUE TITLE
Comparing Excel with a difference (exclude a range from the Matcher)

### ISSUE THREAD

**Issue by tnimni** [tobyweston/simple-excel#9]
Hi,

Is it possible to exclude some cells from the comparison?

attached is my code

    MatcherAssert.assertThat(actual, WorkbookMatcher.sameWorkbook(expected));

Regards,

**Comment by tobyweston** [comment]
Short answer is no.

Sounds like a reasonable thing to do though so we could have a think about how best to do it. 

Pull requests welcome :wink:

**Comment by tnimni** [comment]
Hi,

I managed a work around, taking the workbook and changing the cells I wish to ignore to the same value in memory :)

If I'll have some spare time I'll try to Pull request a better solution

**Comment by tobyweston** [comment]
Closing for now. A PR with some sort of `excluding` matcher would be awesome. So something like:

```
assertThat(workbook, is(sameWorkbook(expected, excluding(range(....))
```
